# Generated by Django 6.0.3 on 2026-04-02 02:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_accPlan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=1)),
                ('segment', models.CharField(max_length=1)),
                ('niche', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tab_fact',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('history', models.TextField()),
                ('description', models.CharField(max_length=45)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flow_direction', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')])),
                ('date', models.DateField(default=datetime.datetime(2026, 4, 2, 2, 15, 8, 198202))),
                ('accPlan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.tab_accplan')),
                ('relation', models.ManyToManyField(to='db.tab_fact')),
            ],
        ),
    ]
