# Generated by Django 6.0.3 on 2026-04-02 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_fact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
