# Generated by Django 6.0.3 on 2026-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_tab_accplan_id_alter_tab_fact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab_accplan',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='tab_accplan',
            old_name='niche',
            new_name='niche_id',
        ),
        migrations.RenameField(
            model_name='tab_accplan',
            old_name='segment',
            new_name='segment_id',
        ),
        migrations.AddField(
            model_name='tab_accplan',
            name='account_label',
            field=models.CharField(default='--empty--', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tab_accplan',
            name='niche_label',
            field=models.CharField(default='--empty--', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tab_accplan',
            name='segment_label',
            field=models.CharField(default='--empty--', max_length=50),
            preserve_default=False,
        ),
    ]
