# Generated by Django 6.0.3 on 2026-04-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc_chart.account')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc_chart.niche')),
                ('segm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc_chart.segment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('acc', 'segm', 'niche'), name='chart_code')],
            },
        ),
    ]
