# Generated by Django 6.0.3 on 2026-04-05 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccPlan',
            fields=[
                ('account_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('account_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('description', models.CharField(max_length=45)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flow_direction', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('accplan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_db.accplan')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentPlan',
            fields=[
                ('segment_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('segment_label', models.CharField(max_length=50)),
                ('related_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_db.accplan')),
            ],
        ),
        migrations.CreateModel(
            name='NichePlan',
            fields=[
                ('niche_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('niche_label', models.CharField(max_length=50)),
                ('related_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_db.segmentplan')),
            ],
        ),
    ]
